# Generated by Django 6.0.4 on 2026-05-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('CURP', models.CharField(max_length=20, unique=True)),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dosis_aplicadas', models.IntegerField()),
                ('lote', models.CharField(max_length=50)),
                ('dosis_requeridas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vacunacion', models.DateField()),
                ('centro_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.centrosalud')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.paciente')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunacion.vacuna')),
            ],
        ),
    ]
